### ISSUE TITLE
exit status 3221225781

### ISSUE THREAD

**Issue by ybbtuubj** [richardwilkes/webapp-example#2]
Thanks for your project.I have encountered a problem now. When I run "main.go", it will prompt "exit status 3221225781".Are there any dll files missing? Looking forward to your reply. Thanks a millon!

**Comment by richardwilkes** [comment]
Assuming you've followed the directions to compile and install the CEF libraries prior to building and running this, there shouldn't be any problems. Certainly nothing with an exit status like that. Unfortunately, you've not given me any real info to go off of. Some details, such as the OS you're using and its version, the exact steps you used (including the steps you took to install the CEF libraries), etc. might be helpful.

**Comment by ybbtuubj** [comment]
Thanks for your reply.  I just ran "build.sh" and it works fine. The previous running error was caused by my direct run of “main.go”, which is my own problem. Thanks again for your project.
